/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzeria;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static pizzeria.Edycja_pizzy.zam;

/**
 *
 * @author Wika
 */
public class Edycja_skladnikow extends javax.swing.JFrame {
     Connection con;
    Statement stmt1, stmt2, stmt3, stmt4, stmt5;
    ResultSet res1, res2, res3, res4, res5;
    DefaultTableModel model;
    static Zamowienia zam;
    float cenam = 0;
    float cenas = 0;
    float cenad = 0;
    //DefaultListModel<String> model1 = new DefaultListModel<>();
    /**
     * Creates new form Edycja_skladnikow
     */
    public Edycja_skladnikow(Zamowienia zam) {
        this.zam = zam;
        initComponents();
         model = (DefaultTableModel) tabelka.getModel();
        panel_edycji.setVisible(false);
        POLE_NOWY_RODZAJ.setVisible(false);
        panel_tabelka_skl.setVisible(false);
    }

    Edycja_skladnikow() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        powrot = new javax.swing.JButton();
        panel_tabelka_skl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelka = new javax.swing.JTable();
        usuń = new javax.swing.JButton();
        edytuj = new javax.swing.JButton();
        dodaj = new javax.swing.JButton();
        panel_edycji = new javax.swing.JPanel();
        wyczysc = new javax.swing.JButton();
        anuluj = new javax.swing.JButton();
        zapisz = new javax.swing.JButton();
        nr = new javax.swing.JLabel();
        cena_mala = new javax.swing.JLabel();
        cena_srednia = new javax.swing.JLabel();
        cena_duza = new javax.swing.JLabel();
        rodzaj = new javax.swing.JLabel();
        nazwa = new javax.swing.JLabel();
        POLE_NUMER = new javax.swing.JTextField();
        POLE_NAZWA = new javax.swing.JTextField();
        POLE_NOWY_RODZAJ = new javax.swing.JTextField();
        POLE_CENA_MALA = new javax.swing.JTextField();
        POLE_CENA_SREDNIA = new javax.swing.JTextField();
        POLE_CENA_DUZA = new javax.swing.JTextField();
        POLE_RODZAJ = new javax.swing.JComboBox();
        nowa_opcja = new javax.swing.JToggleButton();
        komunikat = new javax.swing.JLabel();
        przegladaj = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1239, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        powrot.setText("Powrót");
        powrot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powrotActionPerformed(evt);
            }
        });
        getContentPane().add(powrot, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 104, 41));

        panel_tabelka_skl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelka.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nr", "Nazwa", "Rodzaj", "Cena dla małej pizzy", "Cena dla średniej pizzy", "Cena dla dużej pizzy"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelka);
        if (tabelka.getColumnModel().getColumnCount() > 0) {
            tabelka.getColumnModel().getColumn(0).setMinWidth(30);
            tabelka.getColumnModel().getColumn(0).setPreferredWidth(30);
            tabelka.getColumnModel().getColumn(0).setMaxWidth(30);
            tabelka.getColumnModel().getColumn(2).setResizable(false);
            tabelka.getColumnModel().getColumn(4).setResizable(false);
        }

        panel_tabelka_skl.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 200));

        usuń.setText("Usuń");
        usuń.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuńActionPerformed(evt);
            }
        });
        panel_tabelka_skl.add(usuń, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 105, 36));

        edytuj.setText("Edytuj");
        edytuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edytujActionPerformed(evt);
            }
        });
        panel_tabelka_skl.add(edytuj, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 98, 36));

        dodaj.setText("Dodaj");
        dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajActionPerformed(evt);
            }
        });
        panel_tabelka_skl.add(dodaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 103, 36));

        panel_edycji.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wyczysc.setText("Wyczyść");
        wyczysc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyczyscActionPerformed(evt);
            }
        });
        panel_edycji.add(wyczysc, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 114, 31));

        anuluj.setText("Anuluj");
        anuluj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anulujActionPerformed(evt);
            }
        });
        panel_edycji.add(anuluj, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, 114, 33));

        zapisz.setText("Zapisz");
        zapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapiszActionPerformed(evt);
            }
        });
        panel_edycji.add(zapisz, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, 114, 33));

        nr.setText("Nr");
        panel_edycji.add(nr, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 30, 45, -1));

        cena_mala.setText("Cena dla małej pizzy");
        panel_edycji.add(cena_mala, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        cena_srednia.setText("Cena dla średniej pizzy");
        panel_edycji.add(cena_srednia, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        cena_duza.setText("Cena dla dużej pizzy");
        panel_edycji.add(cena_duza, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, -1, -1));

        rodzaj.setText("Rodzaj");
        panel_edycji.add(rodzaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        nazwa.setText("Nazwa");
        panel_edycji.add(nazwa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        POLE_NUMER.setEnabled(false);
        POLE_NUMER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POLE_NUMERActionPerformed(evt);
            }
        });
        panel_edycji.add(POLE_NUMER, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 43, 30));
        panel_edycji.add(POLE_NAZWA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 110, 30));

        POLE_NOWY_RODZAJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POLE_NOWY_RODZAJActionPerformed(evt);
            }
        });
        panel_edycji.add(POLE_NOWY_RODZAJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 130, 30));
        panel_edycji.add(POLE_CENA_MALA, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 102, 30));
        panel_edycji.add(POLE_CENA_SREDNIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 100, 30));
        panel_edycji.add(POLE_CENA_DUZA, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 100, 30));

        POLE_RODZAJ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        POLE_RODZAJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POLE_RODZAJActionPerformed(evt);
            }
        });
        panel_edycji.add(POLE_RODZAJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, 30));

        nowa_opcja.setText("Nowa opcja");
        nowa_opcja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nowa_opcjaActionPerformed(evt);
            }
        });
        panel_edycji.add(nowa_opcja, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 130, -1));
        panel_edycji.add(komunikat, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 270, 50));

        panel_tabelka_skl.add(panel_edycji, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 990, 160));

        getContentPane().add(panel_tabelka_skl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1010, 470));

        przegladaj.setText("Przeglądaj składniki");
        przegladaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przegladajActionPerformed(evt);
            }
        });
        getContentPane().add(przegladaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 150, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void powrotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powrotActionPerformed
       zam.genUser2();
        zam.setVisible(true);
        dispose();
    }//GEN-LAST:event_powrotActionPerformed

    private void POLE_NOWY_RODZAJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POLE_NOWY_RODZAJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_POLE_NOWY_RODZAJActionPerformed

    private void przegladajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przegladajActionPerformed
        if (przegladaj.isSelected() == true) {
            
            panel_tabelka_skl.setVisible(true);
            czysctabelke();
            przegladaj(model);
        } else {
            
            panel_tabelka_skl.setVisible(false);

        }
    }//GEN-LAST:event_przegladajActionPerformed

    private void POLE_NUMERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POLE_NUMERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_POLE_NUMERActionPerformed

    private void POLE_RODZAJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POLE_RODZAJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_POLE_RODZAJActionPerformed

    private void nowa_opcjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nowa_opcjaActionPerformed
        if (nowa_opcja.isSelected() == true) {
            POLE_NOWY_RODZAJ.setVisible(true);
            POLE_RODZAJ.setEnabled(false);
            POLE_RODZAJ.setSelectedIndex(0);
        } else {
            POLE_NOWY_RODZAJ.setVisible(false);
            POLE_RODZAJ.setEnabled(true);

        }
    }//GEN-LAST:event_nowa_opcjaActionPerformed

    private void usuńActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuńActionPerformed
        int j = tabelka.getRowCount();
        String ostt = tabelka.getValueAt(j - 1, 0).toString();
        int ost = Integer.parseInt(ostt);
        if (tabelka.getSelectedRowCount() > 0) {
            int wiersz = tabelka.getSelectedRow();
            String s = tabelka.getValueAt(wiersz, 0).toString();

            String usunwiersz = "delete from pizzeria.skladniki where id_skladnika=" + s;
            try {
                con = DriverManager.getConnection(
                        "jdbc:derby://localhost:1527/BazaPizzerii", "pizzeria", "pizzeria"
                );
            } catch (SQLException ex) {
                Logger.getLogger(Edycja_pizzy.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                stmt5 = con.createStatement();
                stmt5.executeUpdate(usunwiersz);
                int id1 = Integer.parseInt(s);
                id1++;
                for (int i = id1; i <= ost; i++) {
                    String naprawid = "UPDATE skladniki SET id_skladnika =" + (i - 1) + " WHERE id_skladnika =" + i;
                    stmt5.executeUpdate(naprawid);
                }

            } catch (SQLException ex) {
                Logger.getLogger(Edycja_pizzy.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {//zmienilam
            JOptionPane.showMessageDialog(null, "Nie wybrano wiersza!");//zmienilam
        }//zmienilam

        czysctabelke();
        przegladaj(model);


    }//GEN-LAST:event_usuńActionPerformed

    private void edytujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edytujActionPerformed
         if (tabelka.getSelectedRowCount() > 0) {
              POLE_NAZWA.setText("");
              komunikat.setText("");
       POLE_NOWY_RODZAJ.setText("");
       POLE_RODZAJ.setSelectedIndex(0);
       POLE_CENA_DUZA.setText("");
       POLE_CENA_SREDNIA.setText("");
       POLE_CENA_MALA.setText(""); 
            panel_edycji.setVisible(true);
            int wybrwiersz = tabelka.getSelectedRow();
            int numer = Integer.parseInt(tabelka.getValueAt(wybrwiersz, 0).toString());
            POLE_NUMER.setText(numer + "");
            wypisznazwyrodzajow();
        } else {
            JOptionPane.showMessageDialog(null, "Nie wybrano wiersza!");
        }

    }//GEN-LAST:event_edytujActionPerformed

    private void dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajActionPerformed
        POLE_NAZWA.setText("");
       POLE_NOWY_RODZAJ.setText("");
        komunikat.setText("");
       POLE_RODZAJ.setSelectedIndex(0);
       POLE_CENA_DUZA.setText("");
       POLE_CENA_SREDNIA.setText("");
       POLE_CENA_MALA.setText(""); 
        panel_edycji.setVisible(true);
        int numer = tabelka.getRowCount() + 1;
        POLE_NUMER.setText(numer + "");
        wypisznazwyrodzajow();
    }//GEN-LAST:event_dodajActionPerformed

    private void anulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anulujActionPerformed
         panel_edycji.setVisible(false);
    }//GEN-LAST:event_anulujActionPerformed

    private void wyczyscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyczyscActionPerformed
       POLE_NAZWA.setText("");
       POLE_NOWY_RODZAJ.setText("");
        komunikat.setText("");
       POLE_RODZAJ.setSelectedIndex(0);
       POLE_CENA_DUZA.setText("");
       POLE_CENA_SREDNIA.setText("");
       POLE_CENA_MALA.setText("");
    }//GEN-LAST:event_wyczyscActionPerformed

    private void zapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapiszActionPerformed
        int numer = tabelka.getRowCount() + 1;

        String nazwa = POLE_NAZWA.getText();
        //String skladniki = pobierzwybraneskladniki();
        String rodzaj;
        if (nowa_opcja.isSelected()) {
            rodzaj = POLE_NOWY_RODZAJ.getText();
        } else {
            rodzaj = POLE_RODZAJ.getSelectedItem().toString();
        }
        
        if ((POLE_CENA_MALA.getText() != null && POLE_CENA_MALA.getText().length() > 0) || (POLE_CENA_DUZA.getText() != null && POLE_CENA_DUZA.getText().length() > 0) ||(POLE_CENA_SREDNIA.getText() != null && POLE_CENA_SREDNIA.getText().length() > 0)) {
            try {
                cenam = Float.parseFloat(POLE_CENA_MALA.getText());
                cenas = Float.parseFloat(POLE_CENA_SREDNIA.getText());
                 cenad = Float.parseFloat(POLE_CENA_DUZA.getText());
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, "Niepoprawny format ceny!");
                
            }
        }
       
        if (nazwa.equals("") || rodzaj.equals("") ||  cenam == 0 ||  cenas == 0 ||  cenad == 0 ) {
            komunikat.setText("Brak  danych!");
            komunikat.setForeground(Color.red);

        } else {
            try {
                con = DriverManager.getConnection(
                        "jdbc:derby://localhost:1527/BazaPizzerii", "pizzeria", "pizzeria"
                );
                stmt4 = con.createStatement();
                String insert = "";
                if (tabelka.getSelectedRow() < 0) {
                    insert = "INSERT INTO skladniki VALUES(" + numer + "," + cenam + "," + cenas + "," + cenad + ",'" + rodzaj + "','" + nazwa + "')";
                } else {

                    int wiersz = tabelka.getSelectedRow();
                    String s = tabelka.getValueAt(wiersz, 0).toString();

                    insert = "UPDATE skladniki SET cena_skl_mala=" + cenam + ", cena_skl_srednia=" + cenas + ", cena_skl_duza=" + cenad
                            + ", rodzaj='" + rodzaj + "', nazwa='" + nazwa + "' WHERE id_skladnika=" + s;
                }
                stmt3.executeUpdate(insert);
                komunikat.setText("Nowy składnik został dodany do bazy systemu");
                komunikat.setForeground(Color.DARK_GRAY);
            } catch (Exception e) {
                // JOptionPane.showMessageDialog(null, "Błąd zapisu - brak połączenia z bazą danych");
            }
             POLE_NAZWA.setText("");
       POLE_NOWY_RODZAJ.setText("");
       
       POLE_RODZAJ.setSelectedIndex(0);
       POLE_CENA_DUZA.setText("");
       POLE_CENA_SREDNIA.setText("");
       POLE_CENA_MALA.setText("");
            czysctabelke();
            przegladaj(model);
        }
            
    }//GEN-LAST:event_zapiszActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edycja_skladnikow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edycja_skladnikow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edycja_skladnikow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edycja_skladnikow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edycja_skladnikow().setVisible(true);
            }
        });
    }
     void wypisznazwyrodzajow() {
        try {
            con = DriverManager.getConnection(
                    "jdbc:derby://localhost:1527/BazaPizzerii", "pizzeria", "pizzeria"
            );
            stmt3 = con.createStatement();
            res3 = stmt3.executeQuery(
                    "select distinct(rodzaj) from SKLADNIKI"
            );

        } catch (Exception e) {

        }
        try {
            while (res3.next()) {
                POLE_RODZAJ.addItem(res3.getString("rodzaj"));
            }

        } catch (SQLException ex) {
            Logger.getLogger(NoweZamLok.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    void przegladaj(DefaultTableModel model) {

        try {
            con = DriverManager.getConnection(
                    "jdbc:derby://localhost:1527/BazaPizzerii", "pizzeria", "pizzeria"
            );
            stmt1 = con.createStatement();
            res1 = stmt1.executeQuery(
                    "select * from SKLADNIKI order by id_skladnika"
            );
            stmt2 = con.createStatement();
            res2 = stmt2.executeQuery(
                    "select count(*) from SKLADNIKI "
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Brak połączenia z bazą danych");
        }
        try {

            while (res1.next()) {

                int nr = res1.getInt("id_skladnika");
                String cena_mala = res1.getString("cena_skl_mala") + " zł";
                String cena_srednia = res1.getString("cena_skl_srednia") + " zł";
                String cena_duza = res1.getString("cena_skl_duza") + " zł";
                String rodzaj = res1.getString("rodzaj");
                String nazwa = res1.getString("nazwa");
                
                Object[] row = {nr, nazwa, rodzaj, cena_mala, cena_srednia, cena_duza};
                model.addRow(row);

            }

        } catch (SQLException ex) {
            Logger.getLogger(Edycja_pizzy.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabelka.setModel(model);

    }
 void czysctabelke() {
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField POLE_CENA_DUZA;
    private javax.swing.JTextField POLE_CENA_MALA;
    private javax.swing.JTextField POLE_CENA_SREDNIA;
    private javax.swing.JTextField POLE_NAZWA;
    private javax.swing.JTextField POLE_NOWY_RODZAJ;
    private javax.swing.JTextField POLE_NUMER;
    private javax.swing.JComboBox POLE_RODZAJ;
    private javax.swing.JButton anuluj;
    private javax.swing.JLabel cena_duza;
    private javax.swing.JLabel cena_mala;
    private javax.swing.JLabel cena_srednia;
    private javax.swing.JButton dodaj;
    private javax.swing.JButton edytuj;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel komunikat;
    private javax.swing.JLabel nazwa;
    private javax.swing.JToggleButton nowa_opcja;
    private javax.swing.JLabel nr;
    private javax.swing.JPanel panel_edycji;
    private javax.swing.JPanel panel_tabelka_skl;
    private javax.swing.JButton powrot;
    private javax.swing.JToggleButton przegladaj;
    private javax.swing.JLabel rodzaj;
    private javax.swing.JTable tabelka;
    private javax.swing.JButton usuń;
    private javax.swing.JButton wyczysc;
    private javax.swing.JButton zapisz;
    // End of variables declaration//GEN-END:variables
}
