/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzeria;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Wika
 */
public class Nowy_pracownik extends javax.swing.JFrame {

    Connection con;
    Statement stmtnp1, stmtnp2;
    ResultSet resnp1, resnp2;

    /**
     * Creates new form Nowy_pracownik
     */
    public Nowy_pracownik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        przyciskpowrot = new javax.swing.JButton();
        napisnazwaokienka = new javax.swing.JLabel();
        polenazwisko = new javax.swing.JTextField();
        napisnazwisko = new javax.swing.JLabel();
        poleimie = new javax.swing.JTextField();
        napisimie = new javax.swing.JLabel();
        przyciskdodaj = new javax.swing.JButton();
        napishaslo = new javax.swing.JLabel();
        napispowtorzhaslo = new javax.swing.JLabel();
        polePasswordhaslo1 = new javax.swing.JPasswordField();
        napisadres = new javax.swing.JLabel();
        polePasswordhaslo2 = new javax.swing.JPasswordField();
        napisnumertelefonu = new javax.swing.JLabel();
        napispesel = new javax.swing.JLabel();
        napisemail = new javax.swing.JLabel();
        napisstanowisko = new javax.swing.JLabel();
        wybierzstanowisko = new javax.swing.JComboBox();
        nadpis_dla_hasla = new javax.swing.JLabel();
        nadpis_pesel = new javax.swing.JLabel();
        poletelefon = new javax.swing.JTextField();
        poleadres = new javax.swing.JTextField();
        polepesel = new javax.swing.JTextField();
        poleemail = new javax.swing.JTextField();
        nadpis_telefon = new javax.swing.JLabel();
        komunikat = new javax.swing.JLabel();
        przyciskwyczysc = new javax.swing.JButton();
        panellogowanie = new javax.swing.JPanel();
        napiszaloguj = new javax.swing.JLabel();
        napiskierownik = new javax.swing.JLabel();
        napisHaslo = new javax.swing.JLabel();
        imienazwkier = new javax.swing.JComboBox();
        haslokier = new javax.swing.JPasswordField();
        zaloguj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1370, 720));

        przyciskpowrot.setText("Powrót");
        przyciskpowrot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskpowrotActionPerformed(evt);
            }
        });

        napisnazwaokienka.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        napisnazwaokienka.setText("Dodaj nowego pracownika:");

        napisnazwisko.setText("Nazwisko:");

        napisimie.setText("Imię:");

        przyciskdodaj.setText("Dodaj");
        przyciskdodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskdodajActionPerformed(evt);
            }
        });

        napishaslo.setText("Hasło:");

        napispowtorzhaslo.setText("Powtórz hasło:");

        polePasswordhaslo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polePasswordhaslo1ActionPerformed(evt);
            }
        });

        napisadres.setText("Adres:");

        napisnumertelefonu.setText("Numer telefonu:");

        napispesel.setText("Pesel:");

        napisemail.setText("E-mail:");

        napisstanowisko.setText("Twoje stanowisko:");

        wybierzstanowisko.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Kierownik", "Pracownik", "Administrator" }));
        wybierzstanowisko.setToolTipText("");

        polepesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polepeselActionPerformed(evt);
            }
        });

        przyciskwyczysc.setText("Wyczyść");
        przyciskwyczysc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przyciskwyczyscActionPerformed(evt);
            }
        });

        panellogowanie.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        napiszaloguj.setText("Żeby dodać nowego pracownika zaloguj się jako kierownik:");

        napiskierownik.setText("Kierownik");

        napisHaslo.setText("Hasło");

        imienazwkier.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        haslokier.setText("jPasswordField1");

        zaloguj.setText("Zaloguj się");

        javax.swing.GroupLayout panellogowanieLayout = new javax.swing.GroupLayout(panellogowanie);
        panellogowanie.setLayout(panellogowanieLayout);
        panellogowanieLayout.setHorizontalGroup(
            panellogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellogowanieLayout.createSequentialGroup()
                .addGroup(panellogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panellogowanieLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(napiszaloguj, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panellogowanieLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(panellogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(napiskierownik, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(napisHaslo))
                        .addGap(34, 34, 34)
                        .addGroup(panellogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(haslokier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imienazwkier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panellogowanieLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(zaloguj, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panellogowanieLayout.setVerticalGroup(
            panellogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellogowanieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(napiszaloguj, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panellogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(napiskierownik, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imienazwkier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panellogowanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(napisHaslo)
                    .addComponent(haslokier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(zaloguj, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(komunikat, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(przyciskdodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(przyciskwyczysc, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(410, 410, 410))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(napisemail, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(napisnazwaokienka, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(przyciskpowrot, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(poleemail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(polepesel, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(26, 26, 26)
                                .addComponent(nadpis_pesel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(napisstanowisko, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addComponent(wybierzstanowisko, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(napispesel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(napisnumertelefonu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(napisadres, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(napisnazwisko, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(napishaslo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(napispowtorzhaslo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(napisimie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(poletelefon)
                                    .addComponent(poleimie, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(polenazwisko)
                                    .addComponent(polePasswordhaslo1)
                                    .addComponent(polePasswordhaslo2)
                                    .addComponent(poleadres))
                                .addGap(8, 8, 8)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nadpis_dla_hasla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nadpis_telefon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(69, 69, 69)
                .addComponent(panellogowanie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(425, 425, 425))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(napisnazwaokienka, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(przyciskpowrot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poleimie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(napisimie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(napisnazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(polenazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(napishaslo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(polePasswordhaslo1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(polePasswordhaslo2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(napispowtorzhaslo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(napisnumertelefonu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(poletelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nadpis_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(nadpis_dla_hasla, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(napisadres, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poleadres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(napispesel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(polepesel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nadpis_pesel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panellogowanie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(napisemail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poleemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(napisstanowisko, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wybierzstanowisko, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(przyciskdodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(komunikat, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(przyciskwyczysc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void przyciskpowrotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskpowrotActionPerformed
        Zamowienia zam = new Zamowienia();
        zam.setVisible(true);
        dispose();
    }//GEN-LAST:event_przyciskpowrotActionPerformed

    private void przyciskdodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskdodajActionPerformed
        String HASLO = polenazwisko.getText() + ' ' + poleimie.getText();
        String haslo1 = polePasswordhaslo1.getText();
        String haslo2 = polePasswordhaslo2.getText();
        String TELEFON = poletelefon.getText();
        String ADRES = poleadres.getText();
        String PESEL = polepesel.getText();
        String STANOWISKO = wybierzstanowisko.getSelectedItem().toString();
        String EMAIL = poleemail.getText();
        boolean bledy = false;
        int licznikbledow = 0;
        if (bledy == false) {
            if (haslo1.equals(haslo2)) {
                nadpis_dla_hasla.setText("OK");
                nadpis_dla_hasla.setForeground(Color.DARK_GRAY);

            } else {
                nadpis_dla_hasla.setText("Hasło jest błędne");
                nadpis_dla_hasla.setForeground(Color.red);
                komunikat.setText("Sprawdź wprowadzone dane!");
                komunikat.setForeground(Color.red);
                licznikbledow++;
            }
            int j = 0;
            boolean TylkoLiczbyTelefon = true;
            while ((TylkoLiczbyTelefon == true) && (j < TELEFON.length())) {
                if ((TELEFON.charAt(j) < '0') || (TELEFON.charAt(j) > '9')) {
                    TylkoLiczbyTelefon = false;
                }
                j++;
            }
            if ((TELEFON.length() != 9) || (TylkoLiczbyTelefon == false)) {
                nadpis_telefon.setText("Telefon powinien zawierać 9 cyfr");
                nadpis_telefon.setForeground(Color.red);
                komunikat.setText("Sprawdź wprowadzone dane!");
                komunikat.setForeground(Color.red);
                licznikbledow++;
            } else {
                nadpis_telefon.setText(" ");

            }

            int i = 0;
            boolean TylkoLiczbyPesel = true;
            while ((TylkoLiczbyPesel == true) && (i < PESEL.length())) {
                if ((PESEL.charAt(i) < '0') || (PESEL.charAt(i) > '9')) {
                    TylkoLiczbyPesel = false;
                }
                ++i;
            }
            if ((PESEL.length() != 11) || (TylkoLiczbyPesel == false)) {
                nadpis_pesel.setText("Pesel powinien zawierać 11 cyfr");
                nadpis_pesel.setForeground(Color.red);
                komunikat.setText("Sprawdź wprowadzone dane!");
                komunikat.setForeground(Color.red);
                licznikbledow++;
            } else {
                nadpis_pesel.setText(" ");
            }

        }
        if (licznikbledow == 0) {
            try {
                con = DriverManager.getConnection(
                        "jdbc:derby://localhost:1527/BazaPizzerii", "pizzeria", "pizzeria"
                );
                stmtnp1 = con.createStatement();
                resnp1 = stmtnp1.executeQuery(
                        "select * from PRACOWNICY"
                );

                stmtnp1.executeUpdate("INSERT INTO PIZZERIA.PRACOWNICY (ID_PRAC, LOGIN, HASLO, TELEFON, ADRES, PESEL, STANOWISKO, EMAIL) \n"
                        + "	VALUES (" + id() + ",'" + HASLO + "', '" + haslo1 + "', " + TELEFON + ", '" + ADRES + "', " + PESEL + ", '" + STANOWISKO + "', '" + EMAIL + "')");
            komunikat.setText("Nowy pracownik został dodany do bazy systemu");
                
            } catch (Exception e) {
                System.out.println("nie udalo sie");                
            }
            
            komunikat.setForeground(Color.DARK_GRAY);
            
        }
    }//GEN-LAST:event_przyciskdodajActionPerformed

    private void polePasswordhaslo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polePasswordhaslo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_polePasswordhaslo1ActionPerformed

    private void polepeselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polepeselActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_polepeselActionPerformed

    private void przyciskwyczyscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przyciskwyczyscActionPerformed
        polenazwisko.setText("");
        poleimie.setText("");
        polePasswordhaslo1.setText("");
        polePasswordhaslo2.setText("");
        poletelefon.setText("");
        poleadres.setText("");
        polepesel.setText("");
        wybierzstanowisko.setSelectedIndex(0);
        poleemail.setText("");
        komunikat.setText("");
        nadpis_dla_hasla.setText("");
        nadpis_pesel.setText("");
        nadpis_telefon.setText("");

    }//GEN-LAST:event_przyciskwyczyscActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nowy_pracownik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Nowy_pracownik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField haslokier;
    private javax.swing.JComboBox imienazwkier;
    private javax.swing.JLabel komunikat;
    private javax.swing.JLabel nadpis_dla_hasla;
    private javax.swing.JLabel nadpis_pesel;
    private javax.swing.JLabel nadpis_telefon;
    private javax.swing.JLabel napisHaslo;
    private javax.swing.JLabel napisadres;
    private javax.swing.JLabel napisemail;
    private javax.swing.JLabel napishaslo;
    private javax.swing.JLabel napisimie;
    private javax.swing.JLabel napiskierownik;
    private javax.swing.JLabel napisnazwaokienka;
    private javax.swing.JLabel napisnazwisko;
    private javax.swing.JLabel napisnumertelefonu;
    private javax.swing.JLabel napispesel;
    private javax.swing.JLabel napispowtorzhaslo;
    private javax.swing.JLabel napisstanowisko;
    private javax.swing.JLabel napiszaloguj;
    private javax.swing.JPanel panellogowanie;
    private javax.swing.JPasswordField polePasswordhaslo1;
    private javax.swing.JPasswordField polePasswordhaslo2;
    private javax.swing.JTextField poleadres;
    private javax.swing.JTextField poleemail;
    private javax.swing.JTextField poleimie;
    private javax.swing.JTextField polenazwisko;
    private javax.swing.JTextField polepesel;
    private javax.swing.JTextField poletelefon;
    private javax.swing.JButton przyciskdodaj;
    private javax.swing.JButton przyciskpowrot;
    private javax.swing.JButton przyciskwyczysc;
    private javax.swing.JComboBox wybierzstanowisko;
    private javax.swing.JButton zaloguj;
    // End of variables declaration//GEN-END:variables

    public long id() {
        try {
            con = DriverManager.getConnection(
                    "jdbc:derby://localhost:1527/BazaPizzerii", "pizzeria", "pizzeria"
            );
            stmtnp2 = con.createStatement();
            resnp2 = stmtnp2.executeQuery(
                    "select id_prac from PRACOWNICY"
            );
        } catch (Exception e) {
            
        }
        String id = "0";
        try {
            while (resnp2.next()) {
                id = resnp2.getString("id_prac");

            }
        } catch (SQLException ex) {
        }
        long id_nast = Long.parseLong(id) + 1;
        return id_nast;
    }
}
